github:
  client:
    id: 2d78aa3a5ae6ab3cb770
    secret: f7801ce1f4ccd994d49e51d10269b12b5f120a9a

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: li1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*.xml

logging:
  level:
    root: warn
    com.li.community.mapper: trace
    com.li.community.config.shiro.UserRealm : trace
  pattern:
    console: '%p%m%n'